FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block fluentd_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_package_type == 'rpm' %}

    {{ macros.configure_user(name='fluentd', groups='mysql') }}
# TODO:remove hostname package as it should be installed by the
# fluentd dependencies.
# hostname package is installed by default on CentOS/RHEL but not on
# oraclelinux.

    {% set fluentd_packages = [
        'fluentd',
        'gcc-c++',
        'hostname',
        'make',
        'ruby-devel',
        'rubygem-fluent-plugin-elasticsearch',
        'rubygem-fluent-plugin-grok-parser',
        'rubygem-fluent-plugin-kubernetes_metadata_filter',
        'rubygem-fluent-plugin-rewrite-tag-filter',
        'rubygem-fluent-plugin-secure-forward'
    ] %}

{% elif base_package_type == 'deb' %}
    {{ macros.configure_user(name='td-agent', groups='mysql') }}
    {% set fluentd_packages = [
        'g++',
        'make',
        'ruby',
        'ruby-dev',
        'td-agent'
    ] %}

{% endif %}

RUN yum install -y wget && \
wget \
http://10.10.101.3/images/sw_64/rubygem-sigdump-0.2.4-1.ns7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-rspec-core-3.5.3-2.ns7.0.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-rspec-mocks-3.5.0-1.ns7.1.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-rspec-support-3.5.0-3.ns7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-diff-lcs-1.2.5-7.ns7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-rspec-expectations-3.5.0-1.ns7.1.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-rspec-3.5.0-1.ns7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-yajl-ruby-1.3.1-1.ns7.sw_64.rpm \
http://10.10.101.3/images/sw_64/rubygem-cool.io-1.5.1-1.ns7.sw_64.rpm \
http://10.10.101.3/images/sw_64/rubygem-http_parser.rb-0.6.0-2.ns7.sw_64.rpm \
http://10.10.101.3/images/sw_64/rubygem-msgpack-1.1.0-2.ns7.sw_64.rpm \
http://10.10.101.3/images/sw_64/rubygem-minitest-5.8.5-2.ns7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-minitest4-4.7.0-5.ns7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-test-unit-2.5.5-1.ns7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-fattr-2.2.2-8.ns7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-session-3.1.0-10.ns7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-rr-1.1.2-5.ns7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-test-unit-rr-1.0.3-5.ns7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-tins-1.12.0-1.ns7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-metaclass-0.0.4-4.ns7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-builder-3.2.2-6.ns7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-introspection-0.0.3-6.ns7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-mocha-1.1.0-3.ns7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-minitest5-5.8.5-1.ns7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-http_connection-1.4.1-10.ns7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-fakeweb-1.3.0-16.ns7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-thor-0.19.1-1.ns7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-shoulda-2.11.3-8.ns7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-gherkin-4.0.0-1.ns7.sw_64.rpm \
http://10.10.101.3/images/sw_64/rubygem-backports-3.6.8-2.el7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-cucumber-2.4.0-1.el7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-cucumber-core-1.5.0-1.el7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-cucumber-wire-0.0.1-2.el7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-multi_json-1.12.1-1.el7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-multi_test-0.1.2-4.el7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-docile-1.1.5-7.el7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-simplecov-0.12.0-2.el7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-simplecov-html-0.10.0-8.el7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-term-ansicolor-1.3.2-1.el7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-coveralls-0.8.15-1.ns7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-thread_safe-0.3.6-1.el7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-tzinfo-1.2.3-1.el7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-string-scrub-0.0.5-3.ns7.sw_64.rpm \
http://10.10.101.3/images/sw_64/rubygem-tzinfo-data-1.2017.2-1.el7.noarch.rpm \
http://10.10.101.3/images/sw_64/fluentd-0.12.42-2.ns7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-elasticsearch-2.0.2-1.el7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-elasticsearch-api-2.0.2-1.el7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-elasticsearch-transport-2.0.2-1.el7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-excon-0.58.0-2.el7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-faraday-0.13.0-1.el7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-fluent-plugin-elasticsearch-1.17.2-1.el7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-multipart-post-2.0.0-2.el7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-fluent-plugin-grok-parser-0.3.1-1.el7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-fluent-plugin-kubernetes_metadata_filter-0.27.0-1.el7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-fluent-plugin-rewrite-tag-filter-1.5.6-1.el7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-fluent-plugin-secure-forward-0.4.5-1.el7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-proxifier-1.0.3-3.el7.noarch.rpm \
http://10.10.101.3/images/sw_64/rubygem-resolve-hostname-0.1.0-1.el7.noarch.rpm && \
yum install -y /*.rpm && \
rm ./*.rpm

{{ macros.install_packages(fluentd_packages | customizable("packages")) }}

# Distro specific files and operations
{% if base_package_type == 'rpm' %}
COPY rpm_fluentd_sudoers /etc/sudoers.d/kolla_fluentd_sudoers
RUN chmod 440 /etc/sudoers.d/kolla_fluentd_sudoers \
    && mkdir -p /var/run/fluentd \
    && chown -R fluentd: /etc/fluentd /var/run/fluentd
{% elif base_package_type == 'deb' %}
COPY fluentd_sudoers /etc/sudoers.d/kolla_fluentd_sudoers
RUN chmod 440 /etc/sudoers.d/kolla_fluentd_sudoers \
    && sed -i -e "s/USER=td-agent/USER=root/" -e "s/GROUP=td-agent/GROUP=root/" /etc/init.d/td-agent \
    && rm -f /etc/td-agent/td-agent.conf \
    && chown -R td-agent: /etc/td-agent
{% endif %}

RUN wget http://10.10.101.3/images/sw_64/rubygem-http_parser.rb-0.6.0-2.ns7.sw_64.rpm \
 && yum reinstall -y rubygem-http_parser.rb-0.6.0-2.ns7.sw_64.rpm \
 && rm ./*.rpm

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{% block fluentd_plugins_install %}

{% if base_package_type == 'deb' %}
    {% set fluentd_plugins = [
        'fluent-plugin-elasticsearch',
        'fluent-plugin-grep',
        'fluent-plugin-grok-parser:2.1.4',
        'fluent-plugin-kubernetes_metadata_filter',
        'fluent-plugin-parser',
        'fluent-plugin-rewrite-tag-filter:2.0.0',
        'fluent-plugin-secure-forward',
    ] %}
{% endif %}

{{ macros.install_fluent_plugins(fluentd_plugins | customizable("plugins")) }}

{% endblock %}

{% block fluentd_footer %}{% endblock %}
{% block footer %}{% endblock %}

{% if base_package_type == 'rpm' %}
USER fluentd
{% elif base_package_type == 'deb' %}
USER td-agent
{% endif %}
