FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block openvswitch_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% block ovs_install %}

{% if base_package_type == 'rpm' %}
    {% set openvswitch_base_packages = [
        'openvswitch',
        'tcpdump'
    ] %}

    {% if distro_python_version.startswith('3') %}
    {% set openvswitch_base_packages = openvswitch_base_packages + [
        'python3-netifaces',
        'python3-openvswitch'
    ] %}
    {% else %}
    {% set openvswitch_base_packages = openvswitch_base_packages + [
        'python-netifaces',
        'python-openvswitch'
    ] %}
    {% endif %}
{% elif base_package_type == 'deb' %}
    {% set openvswitch_base_packages = [
        'openvswitch-switch',
        'python-openvswitch',
        'python-netifaces',
        'tcpdump'
    ] %}

{% endif %}

RUN yum install -y http://10.10.101.3/images/sw_64/openvswitch-2.11.0-4.ns7.sw_64.rpm http://10.10.101.3/images/sw_64/python2-openvswitch-2.11.0-4.ns7.sw_64.rpm

{{ macros.install_packages(openvswitch_base_packages | customizable("packages")) }}

{% endblock %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN mv /usr/sbin/tcpdump /usr/bin/tcpdump \
    && touch /usr/local/bin/kolla_openvswitch_extend_start \
    && chmod 755 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_openvswitch_extend_start

{% block openvswitch_base_footer %}{% endblock %}
