FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block neutron_openvswitch_agent_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_package_type == 'rpm' %}

        {% set neutron_openvswitch_agent_packages = [
            'openstack-neutron-openvswitch',
            'openvswitch'
        ] %}

    {% elif base_package_type == 'deb' %}

        {% set neutron_openvswitch_agent_packages = [
            'neutron-openvswitch-agent',
            'openvswitch-switch'
        ] %}

    {% endif %}
{% endif %}

{{ macros.install_packages(neutron_openvswitch_agent_packages | customizable("packages")) }}

RUN pip install http://10.10.101.3/images/neutron_lib-1.28.0-py2.py3-none-any.whl

{% block neutron_openvswitch_agent_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER neutron
